[plugin]
id = "icanthink.alpha_solve_analytical"
name = "Alpha Solve Analytical"
version = "1.0.0"
python_libraries = ["sympy"]

[[functions]]
functionName = "check_equal"

[[functions]]
functionName = "simple_simplify"

[[functions]]
functionName = "solve_ode"

[[functions]]
functionName = "solve_simple"

# Proc macro that evaluates definite integrals
[[proc_macros]]
functionName = "evaluate_integrals"
metaFunctionName = "meta_evaluate_integrals"
